### ISSUE TITLE
Issue with token authorization function

### ISSUE THREAD

**Issue by alexaderosa2** [R-ArcGIS/r-bridge-site#18]
Your instructions have this code block to authorize the arconline token that directs users to use the wrong function to set the token.
```
token <- auth_code()
set_auth_token(token)
```
Based on [this documentation](https://r.esri.com/r-bridge-site/location-services/connecting-to-a-portal.html) I believe the function should be set_arc_token(), this seems to have worked for me.

**Comment by JosiahParry** [comment]
Thank you! That is correct. We changed the name and may have missed some spots!

**Comment by mmachir** [comment]
Thank you! Addressed here: https://github.com/R-ArcGIS/r-bridge-site/pull/30
