### ISSUE TITLE
add_features() error

### ISSUE THREAD

**Issue by witt-andy** [R-ArcGIS/r-bridge-site#33]
I've been using this process and suddenly I cannot update a service, add_features is giving an error: 'rlang::abort()': 'call' must be a call or environment, not a primitive function.

To me this looks like an issue with the function, of course library(arcgis) has been called

![image](https://github.com/user-attachments/assets/ab631faa-932b-4e16-b732-4504ba45d8e6)

**Comment by JosiahParry** [comment]
Thanks for the report, @witt-andy! Can you report the output of `rlang::last_trace()` ? I think there may be a misnamed argument being propagated—in this case my guess is that an argument is being passed as `call` when it shuold probably be `error_call`

**Comment by witt-andy** [comment]
![trace_back](https://github.com/user-attachments/assets/2fe09010-bfee-4c7d-a451-4a707bb5b87c)

Hope this clarifies

**Comment by witt-andy** [comment]
Here's more

![last_trace](https://github.com/user-attachments/assets/8900f8ec-f872-458a-8fb1-6504d54e61a4)

**Comment by JosiahParry** [comment]
It does! Thank you! Have you restarted your R session recently? And would you mind reporting `sessionInfo()` ?

**Comment by witt-andy** [comment]
I restarted and tried the process again but with no luck. Have not changed R versions since this process last executed successfully. Session info follows:

![sessionInfo](https://github.com/user-attachments/assets/49dbeb4a-67b9-4266-ac80-2931b714b5d2)

**Comment by witt-andy** [comment]
Looks like that was what I needed, I'll make sure to bake this into my code to that the utils and layers packages stay refreshed, thanks for working through this with me!

**Comment by JosiahParry** [comment]
whew! awesome. thank you for the update.
