### ISSUE TITLE
Typo in Editing Features tutorial

### ISSUE THREAD

**Issue by nginer316** [R-ArcGIS/r-bridge-site#5]
PERIMTER > PERIMETER

https://github.com/R-ArcGIS/r-bridge-site/blob/30a3779f6be5a3d0a7b1669250779e252b4dc650/location-services/workflows/add-delete-update.qmd#L142

**Comment by mmachir** [comment]
Thanks @nginer316! Fixed here: https://github.com/R-ArcGIS/r-bridge-site/blob/11428a2c62b8f0de5254bffe6a8130b20cac4cf2/docs/editing/update-features.qmd#L9
